name: Android CI

on:

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0

      - name: Setup JDK 17
        uses: actions/setup-java@v3.10.0
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: bash ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.2
        with:
          name: app-debug
          path: app/build/outputs/apk/
